// AUTO-GENERATED by scripts/generate-db-types.cjs
// Source: live PostgreSQL database introspection

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      brands: {
        Row: {
          id: string
          name: string
          logo_url: string | null
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          name: string
          logo_url?: string | null
          sort_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          name?: string
          logo_url?: string | null
          sort_order?: number
          created_at?: string
        }
        Relationships: [
        ]
      }
      customer_products: {
        Row: {
          customer_id: string
          product_id: string
          excluded: boolean
          custom_price: number | null
        }
        Insert: {
          customer_id: string
          product_id: string
          excluded?: boolean
          custom_price?: number | null
        }
        Update: {
          customer_id?: string
          product_id?: string
          excluded?: boolean
          custom_price?: number | null
        }
        Relationships: [
          {
            foreignKeyName: 'customer_products_customer_id_fkey'
            columns: ['customer_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'customer_products_product_id_fkey'
            columns: ['product_id']
            isOneToOne: false
            referencedRelation: 'products'
            referencedColumns: ['id']
          },
        ]
      }
      order_cutoffs: {
        Row: {
          id: string
          cutoff_days: number
          cutoff_time: string
          is_active: boolean
          created_at: string
        }
        Insert: {
          id?: string
          cutoff_days?: number
          cutoff_time?: string
          is_active?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          cutoff_days?: number
          cutoff_time?: string
          is_active?: boolean
          created_at?: string
        }
        Relationships: [
        ]
      }
      order_items: {
        Row: {
          id: string
          order_id: string
          product_id: string | null
          pallet_deal_id: string | null
          quantity: number
          unit_price: number
          line_total: number | null
        }
        Insert: {
          id?: string
          order_id: string
          product_id?: string | null
          pallet_deal_id?: string | null
          quantity?: number
          unit_price: number
          line_total?: number | null
        }
        Update: {
          id?: string
          order_id?: string
          product_id?: string | null
          pallet_deal_id?: string | null
          quantity?: number
          unit_price?: number
          line_total?: number | null
        }
        Relationships: [
          {
            foreignKeyName: 'order_items_order_id_fkey'
            columns: ['order_id']
            isOneToOne: false
            referencedRelation: 'orders'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'order_items_pallet_deal_id_fkey'
            columns: ['pallet_deal_id']
            isOneToOne: false
            referencedRelation: 'pallet_deals'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'order_items_product_id_fkey'
            columns: ['product_id']
            isOneToOne: false
            referencedRelation: 'products'
            referencedColumns: ['id']
          },
        ]
      }
      orders: {
        Row: {
          id: string
          customer_id: string
          delivery_date: string
          status: string
          total: number
          item_count: number
          submitted_at: string | null
          delivered_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          customer_id: string
          delivery_date: string
          status?: string
          total?: number
          item_count?: number
          submitted_at?: string | null
          delivered_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          customer_id?: string
          delivery_date?: string
          status?: string
          total?: number
          item_count?: number
          submitted_at?: string | null
          delivered_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'orders_customer_id_fkey'
            columns: ['customer_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      pallet_deal_items: {
        Row: {
          id: string
          pallet_deal_id: string
          product_id: string
          quantity: number
        }
        Insert: {
          id?: string
          pallet_deal_id: string
          product_id: string
          quantity: number
        }
        Update: {
          id?: string
          pallet_deal_id?: string
          product_id?: string
          quantity?: number
        }
        Relationships: [
          {
            foreignKeyName: 'pallet_deal_items_pallet_deal_id_fkey'
            columns: ['pallet_deal_id']
            isOneToOne: false
            referencedRelation: 'pallet_deals'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'pallet_deal_items_product_id_fkey'
            columns: ['product_id']
            isOneToOne: false
            referencedRelation: 'products'
            referencedColumns: ['id']
          },
        ]
      }
      pallet_deals: {
        Row: {
          id: string
          title: string
          pallet_type: string
          image_url: string | null
          price: number
          savings_text: string | null
          description: string | null
          is_active: boolean
          sort_order: number
          created_at: string
        }
        Insert: {
          id?: string
          title: string
          pallet_type: string
          image_url?: string | null
          price: number
          savings_text?: string | null
          description?: string | null
          is_active?: boolean
          sort_order?: number
          created_at?: string
        }
        Update: {
          id?: string
          title?: string
          pallet_type?: string
          image_url?: string | null
          price?: number
          savings_text?: string | null
          description?: string | null
          is_active?: boolean
          sort_order?: number
          created_at?: string
        }
        Relationships: [
        ]
      }
      product_cutoff_overrides: {
        Row: {
          product_id: string
          cutoff_days: number | null
          cutoff_time: string | null
        }
        Insert: {
          product_id: string
          cutoff_days?: number | null
          cutoff_time?: string | null
        }
        Update: {
          product_id?: string
          cutoff_days?: number | null
          cutoff_time?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'product_cutoff_overrides_product_id_fkey'
            columns: ['product_id']
            isOneToOne: false
            referencedRelation: 'products'
            referencedColumns: ['id']
          },
        ]
      }
      products: {
        Row: {
          id: string
          brand_id: string | null
          customer_id: string | null
          title: string
          pack_details: string | null
          pack_count: number | null
          size_value: number | null
          size_uom: string | null
          price: number
          image_url: string | null
          is_new: boolean
          is_discontinued: boolean
          tags: string[] | null
          case_length: number | null
          case_width: number | null
          case_height: number | null
          sort_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id?: string | null
          customer_id?: string | null
          title: string
          pack_details?: string | null
          pack_count?: number | null
          size_value?: number | null
          size_uom?: string | null
          price: number
          image_url?: string | null
          is_new?: boolean
          is_discontinued?: boolean
          tags?: string[] | null
          case_length?: number | null
          case_width?: number | null
          case_height?: number | null
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          brand_id?: string | null
          customer_id?: string | null
          title?: string
          pack_details?: string | null
          pack_count?: number | null
          size_value?: number | null
          size_uom?: string | null
          price?: number
          image_url?: string | null
          is_new?: boolean
          is_discontinued?: boolean
          tags?: string[] | null
          case_length?: number | null
          case_width?: number | null
          case_height?: number | null
          sort_order?: number
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'products_brand_id_fkey'
            columns: ['brand_id']
            isOneToOne: false
            referencedRelation: 'brands'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'products_customer_id_fkey'
            columns: ['customer_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
      profiles: {
        Row: {
          id: string
          auth_user_id: string | null
          role: string
          business_name: string | null
          contact_name: string | null
          email: string | null
          phone: string | null
          address: string | null
          city: string | null
          state: string | null
          zip: string | null
          access_token: string | null
          show_prices: boolean
          default_group: string
          custom_pricing: boolean
          created_at: string
          updated_at: string
          disabled_at: string | null
        }
        Insert: {
          id?: string
          auth_user_id?: string | null
          role: string
          business_name?: string | null
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip?: string | null
          access_token?: string | null
          show_prices?: boolean
          default_group?: string
          custom_pricing?: boolean
          created_at?: string
          updated_at?: string
          disabled_at?: string | null
        }
        Update: {
          id?: string
          auth_user_id?: string | null
          role?: string
          business_name?: string | null
          contact_name?: string | null
          email?: string | null
          phone?: string | null
          address?: string | null
          city?: string | null
          state?: string | null
          zip?: string | null
          access_token?: string | null
          show_prices?: boolean
          default_group?: string
          custom_pricing?: boolean
          created_at?: string
          updated_at?: string
          disabled_at?: string | null
        }
        Relationships: [
        ]
      }
      schema_migrations: {
        Row: {
          id: string
          applied_at: string
        }
        Insert: {
          id: string
          applied_at?: string
        }
        Update: {
          id?: string
          applied_at?: string
        }
        Relationships: [
        ]
      }
      staff_invites: {
        Row: {
          id: string
          profile_id: string
          email: string
          token_hash: string
          status: string
          created_by: string
          last_sent_at: string
          accepted_at: string | null
          revoked_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          profile_id: string
          email: string
          token_hash: string
          status: string
          created_by: string
          last_sent_at?: string
          accepted_at?: string | null
          revoked_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          profile_id?: string
          email?: string
          token_hash?: string
          status?: string
          created_by?: string
          last_sent_at?: string
          accepted_at?: string | null
          revoked_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'staff_invites_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'staff_invites_profile_id_fkey'
            columns: ['profile_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
        ]
      }
    }
    Views: Record<PropertyKey, never>
    Functions: {
      clone_order: {
        Args: { source_order_id: string; new_delivery_date: string }
        Returns: string
      }
      submit_order: {
        Args: { order_id: string }
        Returns: undefined
      }
    }
    Enums: Record<PropertyKey, never>
    CompositeTypes: Record<PropertyKey, never>
  }
}
